name: Build MYRA APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: unzip -o myra.zip
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Fix Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          ls -la debug.keystore
          # যেখানেই খুঁজুক, সব জায়গায় কপি করে দিলাম
          cp debug.keystore app/debug.keystore || true
      - name: Build APK
        run: gradle assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: MYRA-APK
          path: app/build/outputs/apk/debug/*.apk
